### ISSUE TITLE
Converstion Tests link incorrect.

### ISSUE THREAD

**Issue by WillRubin** [omnibs/elixir-linq-examples#7]
Main page contents link for conversion operators needs plural ("s") at end of link.
...test.esx => ...tests.esx
_(sorry, don't know how to do pull request.)_

**Comment by omnibs** [comment]
Thanks! Fixed here https://github.com/omnibs/elixir-linq-examples/commit/d7c0b337fa976ff552a7e13567b4c36cec8c6321
