### ISSUE TITLE
Use pattern matching instead of elem()

### ISSUE THREAD

**Issue by meadsteve** [omnibs/elixir-linq-examples#8]
I was looking at linq69 (and some others) and I noticed you used elem() to grab part of a tuple. It seems like it would be more idomatic elixir to do something like the following:

``` elixir
product_groups = products
   |> Enum.group_by(fn x -> x.category end)
   |> Enum.filter(fn {category, products} -> products |> Enum.all?(fn p -> p.units_in_stock > 0 end) end)
   |> Enum.map fn {category, products} -> %{category: category, products: products} end
```

What do you think?

**Comment by omnibs** [comment]
Great! I get upset about using elem and hadn't seen the opportunity to use pattern matching there.

Thanks, will update and close soon =]

**Comment by meadsteve** [comment]
:+1: good work by the way.

**Comment by omnibs** [comment]
Done, I was pretty impressed seeing pattern matching worked on cases like 103 and 104!
