### ISSUE TITLE
removes last warnings 

### ISSUE THREAD

**Issue by mindreframer** [omnibs/elixir-linq-examples#9]
https://github.com/ruby2elixir/elixir-linq-examples/commit/d43e5dda91c4a09397e4a62a71e52f5fd6fc0379

but my editor stripped trailing whitespaces, so the diff looks larger that it really is. 

Would you still be interested in merging it? 

Thx for all the examples!

**Comment by omnibs** [comment]
Sure! My fault for the trailing whitespaces.

Fire up a pull request, I'll get your fork and run `mix readme` to see if everything is OK with the generated readme.md file, then I'll merge it.

I will restore [this](https://github.com/ruby2elixir/elixir-linq-examples/commit/d43e5dda91c4a09397e4a62a71e52f5fd6fc0379#diff-f7e1fc31c87a7b14ea67f0b0dfaa6117L174) `IO.puts` though, keeping your new asserts. `mix readme` uncomments the `IO.puts` for the readme.md. It's nice to leave it on the readme to compare with the original C# example, showing for the unfamiliar how we print arrays or nested maps/structs on Elixir.

Thanks for the contribution =]

**Comment by mindreframer** [comment]
Cool, nice trick with mix readme... :) 

https://github.com/omnibs/elixir-linq-examples/pull/10
